Upgrade environment on 2020-10-30
merges https://github.com/manubot/rootstock/pull/383

pandoc-eqnos upgrade addresses the following error:
UnboundLocalError: local variable 'ret' referenced before assignment
https://github.com/tomduck/pandoc-eqnos/issues/43

Hold back pandoc due to the lack of panflute support.

Switch commands in build/README.md to be relative to the repo root.